# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - flask-formapp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # use 3.10 for better package compatibility

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Azure_test/requirements.txt
          echo "Dependencies installed"

      - name: Zip app for deployment
        run: |
          cd Azure_test
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip   # FIXED: Match the zip file name

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for Azure login OIDC
      contents: read    # Required to checkout code

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_76C108ACF06B4EC2A6EDACBE77A2F868 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA26EA1739824B37B1CD019B875FFD97 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B57FE96AAE04C148BFBB54DA48010D2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'flask-formapp1'
          package: .
